### ISSUE TITLE
Copyright infringement in utils.py

### ISSUE THREAD

**Issue by MalcolmSmithUK** [spec-first/connexion#1200]
### Description

This is not an 'April Fools'.  Organisations performing due diligence on open source projects will also see a flag on this repo.

A Black Duck scan has highlighted a copyright infringement on https://github.com/zalando/connexion/blame/master/connexion/utils.py#L65.

The blog post the code is 'stolen from' does not state whether the code is licensed for open source. I understand this issue goes against the best practice of open source contribution.

Originally opened here: https://github.com/zalando/connexion/issues/1199

### Expected behaviour

The code is no longer a copyright infringement for Black Duck scans.

### Actual behaviour

The code is a copyright infringement for Black Duck scans.

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by jmcs** [comment]
I'm not a lawyer, but that single line of code seems to fall well within the definition of trivial. If it wasn't the simple refactoring you did in #1201 would not remove the copyright violation.

**Comment by MalcolmSmithUK** [comment]
I'm not sure that 'trivial' is even 'trivial' enough to describe this one.  I'm sure this flag doesn't make any sense to you, I or any other contributors.   

The code only uses Python, the composition as a one-liner is what's documented in the blog post.  I can't reverse engineer the flag, but perhaps even removing the word 'stolen' may have done it. 

I don't want to take up any one's time handling this, but I hope you'll understand that this has become quite pressing within our organisation. We have a number of projects which make use of Connexion and there may be other organisation affected by this scan in the future.

**Comment by jmcs** [comment]
Copyright is about unique intellectual contributions, it's not about literal copies of something - as I said the changes you did in #1201 don't substantially change the "content" of the function, it just fools an automatic scan. If your organization is concerned about one version, they should definitely be concerned about the other, regardless of what an automated checker says, and consult a lawyer.

**Comment by antonyedwards** [comment]
Hi ... sorry ... I posted this on #1199 which I just realised is closed so reposting here. I'm part of Malcolm's team and have been reviewing the BlackDuck scan. Yes, I was really hoping it was a joke too, but no, they are serious. Just to show you exactly how it was flagged ...

This is how it was shown on the summary view:
![image](https://user-images.githubusercontent.com/2156250/78242650-48207280-74da-11ea-894e-d43e1d272bfe.png)

And then in the details tab it was shown as this:
![image](https://user-images.githubusercontent.com/2156250/78242709-6d14e580-74da-11ea-859d-b28864cf9847.png)

So basically it's saying that on line 65 of utils.py it's detected some unlicensed code.

Obviously we don't know how BlackDuck really works, but from what it's found I think it is mainly looking at headers and comments and looking for anything that suggests cut-and-paste code. 

FWIW ... I did speak to two lawyers about it when it first came up. They generally agreed with me that one line of code could be considered an "excerpt" under copyright law. The UK lawyer also said that under UK law since the original code was clearly presented for others to use it could be argued that it has an "implied license". The US lawyer didn't think this would work in the US.

So from a legal perspective this is definitely "low risk", but it's not totally clean and someone could still argue it if they wanted, and so given that it's only one line the simplest solution seemed a "clean-room" implementation which is what we've done and which definitely removes any copyright issues (even though by nature there is going to be functional equivalence).

Apologies since this feels so trivial, but really would appreciate any support that prevents us having to do some kind of patching. I also figure that others may have similar issues at some point and this change would save them the effort we've been through talking to lawyers. Many thanks.
