### ISSUE TITLE
Get the jwt from another field from header

### ISSUE THREAD

**Issue by mohameds786** [spec-first/connexion#1244]
### Description
Hello.

I am using connexion for API.
Actually I have generated python code for an API which use jwt token for security.
The jwt token is got from the "Authorization" parameter of the request header.
Is it possible to customize this behavior in order to get it from another parameter?

### Expected behaviour
Imagine that in the HTTP header I have 
Authorization: "something but not the jwt"
JWT-Authorization: "something which is the jwt"

When I call an operation of my API, I want the security_controller to get "something which is the jwt" as the JWT but actually it takes "something but not the jwt"

Does someone have an idea?

Thank you very much

**Comment by apatap** [comment]
Connexion honors the OpenAPI specification. So simply

**Comment by apatap** [comment]
Since [bearer authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/) requires a header called "Authorization", how about using [api key authentication](https://swagger.io/docs/specification/authentication/api-keys/), where the header name can be freely chosen.

In this [example](https://github.com/zalando/connexion/tree/0989a93df502ac5d84fb694d75ae88a665700493/examples/openapi3/apikey)  "X-Auth" is used as header name.

**Comment by RobbeSneyders** [comment]
This is according to spec.
