### ISSUE TITLE
ExtraParameterProblem and UnsupportedMediaTypeProblem should be subtypes of a general 4XX error class

### ISSUE THREAD

**Issue by macdjord** [spec-first/connexion#1414]
### Description

The exception classes `ExtraParameterProblem` and `UnsupportedMediaTypeProblem` are both raised by the validator code to represent specific cases of requests not conforming to the declared API, namely receiving parameters which are not declared in the API and receiving media of a non-JSON format to a JSON-only endpoint respectively. Logically, they should therefore be subtypes of `BadRequestProblem`, which is the exception raised by the validator code to represent all other kinds of non-conforming requests, e.g. missing or wrongly-typed parameters.

### Expected behaviour

`app.add_error_handler(BadRequestProblem, my_bad_request_handler)` should cause *all* errors raised by Connexion in response to invalid API requests to be processed by `my_bad_request_handler()`

### Actual behaviour

It is necessary to register error handlers for `ExtraParameterProblem` and `UnsupportedMediaTypeProblem` explicitly as well.

### Steps to reproduce

* Create an API with `strict_validation` enabled, with an endpoint that accepts only JSON request body and takes a single parameter named 'foo'
* Register an error handler for `BadRequestProblem`
* Call the endpoint with a request body of a non-JSON type or with a parameter named 'bar'
* Note that the registered error handler is *not* call

### Additional info:

N/A

**Comment by RobbeSneyders** [comment]
Thanks @macdjord.

I agree that this would make sense for the `ExtraParameterProblem`, since both return a 400 status code, and the `ExtraParameterProblem` can be interpreted as a `BadRequestProblem` with additional information. The `UnsupportedMediaTypeProblem` represents a 415 error though, which is different from a bad request.

We could make it easier to catch client errors by creating an abstract `ClientErrorProblem` class to represent any 4xx error and have all 4xx problems subclass it instead.
