### ISSUE TITLE
Connexion doesn't declare setuptools dep

### ISSUE THREAD

**Issue by jmcrawford45** [spec-first/connexion#1479]
### Description
Connexion doesn't declare setuptools as a dep, but it uses it

### Expected behaviour
connexion can successfully be imported

### Actual behaviour
ImportError: No module named pkg_resources

### Steps to reproduce
Build a [pex](https://pex.readthedocs.io/en/v2.1.70/) with connexion as a dep and try to import it

### Additional info:

Output of the commands:

- `python --version`
 Python 3.7.9
- `pip show connexion | grep "^Version\:"`
2.7.0

**Comment by RobbeSneyders** [comment]
Hi @jmcrawford45 
Thanks for the report. `setuptools` is usually installed by default, but since we depend on `pkg_resources`, it would be good to add it explicitly.

An even better solution would be to [replace `pkg_resources` with `importlib`](https://setuptools.pypa.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources) though.
