### ISSUE TITLE
populate routes with gunicorn (connexion 3.0.0a7)

### ISSUE THREAD

**Issue by jdkent** [spec-first/connexion#1755]
### Description
When starting the flask app with gunicorn, the connexion app does not initialize routes. Is there another way to initialize the connexion app while running the flask app with gunicorn?

example:

```python
import logging
from pathlib import Path

import connexion
from connexion.resolver import MethodViewResolver

logging.basicConfig(level=logging.INFO)

zoo = {
    1: {
        "id": 1,
        "name": "giraffe",
        "tags": ["africa", "yellow", "hoofs", "herbivore", "long neck"],
    },
    2: {
        "id": 2,
        "name": "lion",
        "tags": ["africa", "yellow", "paws", "carnivore", "mane"],
    },
}


app = connexion.FlaskApp(__name__, specification_dir="spec/")

options = {"swagger_ui": True}
app.add_api(
    "openapi.yaml",
    options=options,
    arguments={"title": "MethodViewResolver Example"},
    resolver=MethodViewResolver(
        "api",
        # class params are entirely optional
        # they allow to inject dependencies top down
        # so that the app can be wired, in the entrypoint
        class_arguments={"PetsView": {"kwargs": {"pets": zoo}}},
    ),
    strict_validation=True,
    validate_responses=True,
)

# get access to the flask app
flask_app = app.app

if __name__ == "__main__":
    app.run(f"{Path(__file__).stem}:app", port=8080)
```

Then I ran gunicorn
```bash
gunicorn -w 1 -b :8080 app:flask_app --log-level debug --timeout 120
```

### Expected behaviour

`http://localhost:8080/openapi/pets`

would show pets

### Actual behaviour

{
"type": "about:blank",
"title": "Not Found",
"detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
"status": 404
}

### Steps to reproduce

run script above

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by jdkent** [comment]
needed to use uvicorn worker-class :laughing: 

```bash
gunicorn -w 1 -b :8080 app:flask_app --log-level debug --timeout 120 --worker-class uvicorn.workers.UvicornWorker
```

**Comment by RobbeSneyders** [comment]
Thanks @jdkent, will add this to the documentation.

**Comment by adamnovak** [comment]
It looks like you also need to set the `worker_class` option programmatically when running a Connexion-ified Flask app with Gunicorn from within a Python program via an implementation of Gunicorn's `BaseApplication`. Otherwise only things added directory to the `.app` member of the Connexion application actually work. You need it to be part of `options` in the `BaseApplication`'s `__init__`, if you follow the [Gunicorn example](https://docs.gunicorn.org/en/stable/custom.html).

The Connexion docs don't really cover setting up a production-y, Gunicorn setup from within Python, so it took a while to work this out.
