### ISSUE TITLE
[Connexion 3.0.0 config] Migration from flask.current_app.config

### ISSUE THREAD

**Issue by vladislavkoz** [spec-first/connexion#1804]
With connexion 2 it was pretty easy to configure some variables that can be accessed from any place in the app. 
We were able to pass these variables to the flask config and then do:

```
from flask import current_app
config = current_app.config
```
"config contains everything what we need"

How we can achieve the same using the connexion 3?

**Comment by Parthib** [comment]
Did you get a resolution on this question? I was wondering the same thing

**Comment by vladislavkoz** [comment]
@Parthib  We used "from connexion.context import scope" and implemented our own interface for managing things inside this virtual context so it would be easier to switch in the future if any breaking updates like this one as we had to refactor a lot of things.

**Comment by uniqueg** [comment]
Facing the exact same problem. Would you mind expanding on the solution you came up with @vladislavkoz? Or, ideally, would you share it? Maybe it's something that could be worth including in the Connexion 3 cookbook (documentation is really a bit lacking at this point). I guess using `current_app` for that purpose is not an uncommon pattern...

**Comment by vladislavkoz** [comment]
@uniqueg See my last [comment](https://github.com/spec-first/connexion/issues/1804#issuecomment-1879351018)

**Comment by uniqueg** [comment]
Well, I guess I was hoping that you would share your Middleware class (or a reduced version focusing just on the use case that this issue is about, i.e., making config parameters available in application/runtime context), because l, given the current sparsity of the Connexion documentation in terms of concrete examples and the huge conceptual and technical differences between v2 and v3, it's not exactly trivial.

Fine if you can't or don't want to, of course, whatever the reason. But _if_ you can, I think it would be useful for a lot of Connexion users, and it could form a basis for a potential new default middleware or an addition to the cookbook.

**Comment by vladislavkoz** [comment]
@uniqueg 
It's just super simple, nothing special so I thought that it's clear what todo.

```
from connexion.context import scope

SERVICE_CONTEXT_KEY = "service_context"

class ServiceContext:
    @staticmethod
    def _get_request_context_value(key):
        if scope:
            return scope.get(SERVICE_CONTEXT_KEY, {}).get(key)

    @staticmethod
    def _set_request_context_value(key, value):
        service_context = scope.get(SERVICE_CONTEXT_KEY)
        if not service_context:
            scope[SERVICE_CONTEXT_KEY] = {}
        scope[SERVICE_CONTEXT_KEY][key] = value
```

**Comment by vladislavkoz** [comment]
BTW, there is also available

from connexion import request as connexion_request

**Comment by uniqueg** [comment]
Thanks a lot @vladislavkoz, I find this very useful. Will probably try to make this into a middleware and add it before exception handling. If so, I'll post here what I did.
