### ISSUE TITLE
Upload of multiple files via multipart/form-data broken in connexion 3

### ISSUE THREAD

**Issue by kordian2k** [spec-first/connexion#1806]
### Description
An endpoint specified for the upload of multiple files, e.g.,
```
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          hashes:
            type: array
            items:
              type: string
          files:
            type: array
            items:
              type: string
              format: binary
```

always triggers a validation error similar to the following:

> Validation error: '' is not of type 'array' - 'files'
BadRequestProblem(status_code=400, detail="'' is not of type 'array' - 'files'")

The validation does not throw errors for an endpoint specified for a single file, i.e.,

```
files:
  type: string
  format: binary
```

### Additional info:

The implementation of the `_parse` method in `FormDataValidator` in [form_data.py](https://github.com/spec-first/connexion/blob/b244d809089eb584ce3e9661d619ed5564ca4103/connexion/validators/form_data.py) replaces the uploaded file data with an empty string. Hence, the validation encounters a string and not an array as shown in the error message above.

Output of the commands:

- `python --version` 3.11.3
- `pip show connexion | grep "^Version\:"` 3.0.1
- I use the `AsyncApp` in my application.

**Comment by kordian2k** [comment]
Hi @RobbeSneyders . I can prepare a PR to fix the validation.

However, I do not fully understand the motivation to remove the file references from the body. In particular, the docs recommend to use the AsyncApp, even when writing synchronous view functions. How would I retrieve the files in this case if the references are deleted or only kept as awaitables?

**Comment by RobbeSneyders** [comment]
The files are only replaced for validation.

The files are injected in your Python view functions directly. If you're using the `FlaskApp`, the files are provided as [werkzeug.FileStorage](https://werkzeug.palletsprojects.com/en/3.0.x/datastructures/#werkzeug.datastructures.FileStorage) instances. If you're using the `AsyncApp`, they're provided as [Starlette.UploadFile](https://www.starlette.io/requests/#request-files) instances. 

Swagger 2:
```yaml
  /test-formData-file-upload:
    post:
      summary: 'Test formData with file type, for file upload'
      operationId: hello.formdata_file_upload
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```

OpenAPI 3:
```yaml
  /test-formData-file-upload:
    post:
      summary: 'Test formData with file type, for file upload'
      operationId: hello.formdata_file_upload
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```

FlaskApp:
```python
def formdata_file_upload(file):
    # file = [werkzeug.FileStorage()]
```

AsyncApp:
```python
def formdata_file_upload(file):
    # file = [starlette.UploadFile()]
```

Note that `file` is currently always a list of files since Connexion accepts multiple files for a parameter, even if its type is `type:string` instead of `type:array`.

We might want to change this as part of this fix as well. So `file` is only an array for specs with `type: array`, and is a single file for specs with `type: string`.

We should also document this in the [request / parameter handling documentation](https://connexion.readthedocs.io/en/latest/request.html).

**Comment by jerryc05** [comment]
encountered same error, hopefully this gets fixed soon
