### ISSUE TITLE
Help with using GZipMiddleware in Connexion 3

### ISSUE THREAD

**Issue by alfechner** [spec-first/connexion#1849]
I want every response from my app to be compressed. I setup my connexion 3 app with `GZipMiddleware` like so:

```python
app.add_middleware(GZipMiddleware, minimum_size=0)
```

But on request I receive this error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I'm not sure if I do something wrong, do I need to set the encoding somehow?

I would be very thankful for any guidance on this.

**Comment by feteu** [comment]
I strongly assume the issue is because the **GZipMiddleware** is being introduced _after the validation_ (default middleware positioning). See also here in the [documentation](https://connexion.readthedocs.io/en/3.0.5/middleware.html#middleware-order)

I made it work while specifying the order of the **GZipMiddleware**, loading it _before the validation_, like this...

```python
from connexion import AsyncApp
from connexion.middleware import MiddlewarePosition

# ...

app = AsyncApp(__name__, specification_dir="./spec/")
app.add_api("openapi.yaml")

# ...

app.add_middleware(GZipMiddleware, MiddlewarePosition.BEFORE_VALIDATION, minimum_size=1000)

# ...
```

As soon as I find some time, I'll try to document different middleware implementations accordingly.

**Comment by alfechner** [comment]
Thanks @feteu for the quick answer. Indeed, you were right, that solves the issue.
