### ISSUE TITLE
It feels like this project is still on Summer holiday

### ISSUE THREAD

**Issue by chrisinmtown** [spec-first/connexion#1973]
### Description

I don't see any activity over the summer, the last PR response seems to be dated 27 May 2024 and the last commit was made 30 May 2024. I see over a hundred open issues and twenty open pull requests, most without a response from a maintainer.

### Expected behaviour

Maintainers respond to issues and pull requests eventually.

### Actual behaviour

Unfortunately for my project and my little team, radio silence.

### Steps to reproduce

Gosh. I sure don't mean to be rude here. I know everyone is a volunteer.

### Additional info:

We depend on connexion for some revenue-generating features, and I'm very interested in continuing to use it. 

Please share your thoughts on the situation, like what level of activity the maintainers can sustain.

Thanks for listening.

**Comment by alanbchristie** [comment]
I too am getting concerned.

**connexion** is a neat but crucial framework for us, but with @RobbeSneyders and others not having made any changes for more than 3 months I am beginning to suspect the project's stalled.

**Comment by mfmarche** [comment]
I created a PR #1967 to get the CVE stuff addressed. It would be great if that could be reviewed and/or accepted into the v2 branch and then released to pypi.

**Comment by RobbeSneyders** [comment]
Hi all, sorry for the radio silence and thanks for raising this issue.

Both @Ruwann and I have recently become first-time fathers, significantly reducing our time available for connexion since we maintain it almost entirely in our free time.

Our time will still be limited in the coming period, but I'll try to make time to review PRs so others can contribute. If there are people consistently contributing, we are happy to welcome them to the team.

---

> I see over a hundred open issues

FYI, we reduced the open issues from 400+ to 100 in the past two years, so this is not as bad as it looks :sweat_smile:

**Comment by LewisCowlesMotive** [comment]
I too felt a bit ungrateful. We pivoted to FastAPI, because the org we are working with in Python decided that things will be better with just fastAPI. I'm sorry that I've not been able to help out on issues I've raised, and sorry that you both have this pressure.

Congratulations on your bundles of joy. Thank you for all the literally free beers. It's been great using Flask for this time, and adding spec-first principles (and gaining the language of "spec-first") to say "no don't auto-generate the docs, curate them".

**Comment by chrisinmtown** [comment]
For all of you who depend on connexion as I do, and who are invested enough to notice and comment on this issue ;) I'd like to suggest you watch this project (if you're not watching it already). Then you get notifications about new issues, new PRs and etc.  I am watching this project, reviewing PRs and trying to contribute where I can to make my interest clear. If fellow users review PRs, maybe we can shorten the time those PRs get resolved? The activity level here is modest so the time required has also been modest.  Please consider, thanks for reading this and happy new year.
