### ISSUE TITLE
Default value for nested object

### ISSUE THREAD

**Issue by worldmind** [spec-first/connexion#375]
I try set default value for nested object in swagger.yml, but it does not work, simple example here
https://github.com/worldmind/connexion-example/commit/09d94ed79491d4593154681b047f8e8ceaca1438

**Comment by hjacobs** [comment]
Yes, this is a missing feature (or other people would call it a bug).

**Comment by tommyjcarpenter** [comment]
I almost filed an identical issue.. luckily I found this first. Yes I have a top level parameter that is an object and an inner parameter with a  default and that default is not honored by connexion.

**Comment by hjacobs** [comment]
@tommyjcarpenter willing to work on a fix/PR?

**Comment by tommyjcarpenter** [comment]
Maybe.. do you know where in the codebase changes are needed, and have a guide how to run your tests? Don’t have time to learn while codebase

**Comment by LienM** [comment]
Is this still an open issue? Where should I start looking if I want to fix this?

**Comment by M-Reimer** [comment]
This is still an issue. IMHO this should have a higher prio. Actually with this bug it is useless to define defaults at all.

**Comment by M-Reimer** [comment]
Can someone at least give some pointers on where this would have to be patched? Where can I get the set default value? How can I store it? Where do I have to apply it to the dict?

**Comment by joe42** [comment]
This feature would be highly appreciated specifically for the request body schema definition. 
Could you maybe add a warning in the documentation that this does not work for now?

I have been working with connexion for almost two years now and assumed that this works out of the box. Since we set attributes explicitly for responses in our case it is only relevant to have defaults for requests. This would make it really easy to set defaults in a declarative way that is automatically documented and does not require additional code.

**Comment by M-Reimer** [comment]
For my own project, I've hacked together a helper class which parses the yaml file again and applies the default values.

But as this project seems to [be](https://github.com/zalando/connexion/issues/1262) [dead](https://github.com/zalando/connexion/issues/1334), I'm on my way of searching an alternative.

**Comment by joe42** [comment]
> But as this project seems to be dead, I'm on my way of searching an alternative.
Sound advice. It's hard to find a good production ready alternative atm. Hopefully someone will pick up the project again. I think it is still one of the best solutions.

**Comment by RobbeSneyders** [comment]
Closing in favor of #351
