### ISSUE TITLE
pythonic support for operationId to function mapping

### ISSUE THREAD

**Issue by bits01** [spec-first/connexion#520]
### Description
Connexion supports `pythonic_params=True` for function parameters. It should also support pythonic function names derived from an `operationId`, e.g. if the operationId is `lowerCamelCase` it should be serviced by a function named `lower_camel_case`

### Expected behaviour
Support pythonic operationId -> function name mapping

### Actual behaviour
Does not find function if not named exactly like the `operationId`

### Additional info:

Output of the commands:

- `python --version`
Python 2.7.14

- `pip show connexion | grep "^Version\:"`
Version: 1.1.15

**Comment by bobh66** [comment]
That can be done with a custom Resolver.  Define a class that inherits from Resolver and a method that converts the operationId in camel case to the function/method format you want, and return that method.  Use your custom resolver class when you add_api to the app object.

**Comment by bits01** [comment]
I see. Should such a Resolver implementation be provided out of the box? It sounds like a pretty common use case.

**Comment by bits01** [comment]
Is the custom Resolver called on every API call or only once per operation and the result is cached? Thinking performance if using regexp in a resolver implementation for example.

**Comment by bobh66** [comment]
I don't know if it "should" be provided out of the box, but you could submit a PR and see if it is accepted.  The RestyResolver could be used as an example of a custom Resolver.

I can't recall if the resolver is called per request or only at startup.  I want to say it's only called once for each operation ID during initialization, but I could be wrong.

**Comment by vimalloc** [comment]
As the operationId is meant for the backend, I feel like giving it the exact function name instead of swapping between camalCase and underscores is the least surprising thing that could happen.  Why do you want to use camalCase here in the first place?

**Comment by bits01** [comment]
Because the swagger file can also be used to generate client side code and we're standardized on using camelCase for JSON and YAML. Someone who downloads our swagger file should not care what the backend is implemented in hence shouldn't see underscores in the operationId, for consistency with the rest of the swagger file.

**Comment by bits01** [comment]
After playing with it some more, `Resolver` is the right way to do it indeed and it seems that `Resolver.resolve_operation_id()` only gets called once per `operationId` at startup, so it's OK if it abuses slower things like regexp.

I'd still like to see the "stock" Resolver enhanced to support a `pythonic_names` option.

**Comment by hjacobs** [comment]
@bits01 I see your point regarding using the Swagger/OpenAPI YAML for other use cases (client generation) --- I think we would be happy to accept a contribution if you are willing to work on a PR :smile:

**Comment by bits01** [comment]
I am very new to the python world, so I will need some hand holding.
My idea is to add an option to `add_api()` just like it currently has `pythonic_params`, e.g. `pythonic_funcs` that gets piped to the existing `Resolver` as an option that defaults to `False` to not change the current behavior. The existing `Resolver` can then apply a regexp to the `operationId` and convert it from camelCase --> under_scores.

Or should there be a single option `pythonic_names` that implies both params and function names? I would think this is the more popular use case, someone would want both not a mixture.

**Comment by macdjord** [comment]
@bits01 Are you using automatic routing or explicit routing?

If you're talking about automatic routing, then I agree that it would be useful to have an option on `RestyResolver` to automatically convert camelCase names extracted from the path into snake_case names in the auto-generated object ID.

On the other hand, if you're talking about explicit routing, then I disagree. The purpose of the `objectID` field in the API specification is to map an endpoint to the Python function used to call it. It is a _Python_ identifier (or rather a Python object reference, i.e. a sequence of identifiers joined with dots), *not* a YAML identifier of key; as far as the YAML file is concerned, it is arbitrary string data.

It makes no sense to try to convert the ID into 'Python format' since the correct value depends not only on the function name but the structure of your project. For example, `objectID: "backend.server.SearchByDates.find_range` - `backend` being the package in which all my API-servicing code is organised, `server` being a module inside that package which handles all the server-related endpoints, `SearchByDates` being a class in that module which handles this specific endpoint, and `find_range` being the class method which serves GET requests on the endpoint.

If its important to you to keep your Python identifiers out of your API definitions, then you should implement that mapping *in Python* and use an appropriate custom resolver to handle the translation.
