### ISSUE TITLE
How to validate data if swagger-spec has consumer other than 'json' type

### ISSUE THREAD

**Issue by sidhujasminder** [spec-first/connexion#655]
### Description
Not an issue more of a question of which i could not find a solution. 
Here's my swagger spec:

```json
"/endpoint1/": {
 "post": {
        "consumes": [
          "application/json",
          "multipart/form-data"
        ],
```

When i give my request for the following endpoint i can give input in 2 formats. For application/json type input i depend on connexion.decorator.validation to do the validation and for the 'multipart/form-data', i am currently doing the manual check which although same type of data but in a file.

### Expected behaviour
I expect that connexion recognises what type of request is it of the two. And if it is application/json it should validate rather than skipping it.

Is there a way to get the checks done?

### Actual behaviour
Skipping the validation for data type being application/json.

### Steps to reproduce
Just create a simple endpoint which consumes `application/json` and `multipart/form-data`.
Now pass the application/json data and you see that request body is not validated to the defined schema.

https://github.com/zalando/connexion/blob/master/connexion/decorators/validation.py#L101, For me this line is the problem, where multipart mimetype is rejected for validation.

### Additional info:

Output of the commands:

- `python --version` `Python 3.6.5`
- `pip show connexion | grep "^Version\:"` - `Version: 1.1.15`

**Comment by dtkav** [comment]
Hey @sidhujasminder this is a known limitation of connexion at the moment (but still a major bummer).

I think this will be a backwards-incompatible change because right now the server relies on the `consumes` field in the specification to deserialize the data, and ignores the client's content-type headers. It should be using both. There are probably many users who aren't providing any content-type headers.

I can try to address it in the dev-2.0 branch.

Thanks for raising the issue.

**Comment by RobbeSneyders** [comment]
Fixed in https://github.com/spec-first/connexion/pull/1588
