### ISSUE TITLE
support non-default APPLICATION_ROOT in swagger-ui

### ISSUE THREAD

**Issue by WouterVH** [spec-first/connexion#660]
In my flask's config I have a non-default APPLICATION_ROOT

APPLICATION_ROOT = "myapp"
base_path = "/api/v1"

my swagger-UI is then correctly available at url:
http(s):<hostname>/<APPLICATION_ROOT>/api/v1/ui/

and the swagger.json correctly available at:
http(s):<hostname>/<APPLICATION_ROOT>/api/v1/swagger.json

but the swagger itself  shows Error 401
and searches for the json at  http(s):<hostname>/api/v1/swagger.json
instead of  http(s):<hostname>/<APPLICATION_ROOT>/api/v1/swagger.json

### Additional info

python version: 3.5 + 3.6
Connexion v1.4.2

**Comment by dtkav** [comment]
#568 might solve your problem.

The go-forward plan is to remove the vendored swagger-ui in connexion 2.0 (see #406), so that change probably won't get merged.

The `dev-2.0` branch depends on https://github.com/dtkav/swagger_ui_bundle at the moment.
The url is passed here: https://github.com/zalando/connexion/blob/dev-2.0/connexion/apis/flask_api.py#L284

Any idea how to generate the correct URL from within Flask?

**Comment by rafaelcaricio** [comment]
Is this still a valid issue in connexion 2 ? cc @dtkav or @WouterVH

**Comment by dtkav** [comment]
I believe this will be fixed with #823 but I was unable to get feedback. I can pick it up again if you're willing to take a look at it.

**Comment by rafaelcaricio** [comment]
Hey @dtkav,
Yes, I will review your PR and give feedback on it then. Thank you!
