### ISSUE TITLE
2.0 swager_ui kwarg for app and add_api

### ISSUE THREAD

**Issue by martinitus** [spec-first/connexion#742]
### Description
It seems like the documentation of https://github.com/zalando/connexion/tree/dev-2.0#the-swagger-ui-console needs to be fixed for 2.0.

### Expected behaviour
```
app = connexion.App(__name__, specification_dir='.', swagger_ui=False)
app.add_api('../templates/api3.yaml', resolver=RestyResolver('api'), strict_validation=strict_validation,swagger_ui=True)
```
works as documented

### Actual behaviour
The above code fails for me with 

```
Error
Traceback (most recent call last):
  File "<removed>\Python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "<removed>\Python\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "<removed>\test\api\server.py", line 35, in test_launch
    thread = foo.api.run_api_server()
  File "<removed>\api\__init__.py", line 18, in run_api_server
    app = connexion.App(__name__, specification_dir='.', swagger_ui=False)
  File "<removed>\venv\lib\site-packages\connexion\apps\flask_app.py", line 21, in __init__
    super(FlaskApp, self).__init__(import_name, FlaskApi, server=server, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'swagger_ui'
```
Similar for the second kwarg.

### Additional info:

Output of the commands:

- `python --version` : 3.6.6
- `pip show connexion | grep "^Version\:"` Version: 2.0.0rc5

**Comment by dtkav** [comment]
Thanks for the bug report!
Please see #743 , and let me know if I missed anything.

**Comment by kigonya** [comment]
have had to freeze our code at 1.5.3 for now...  changing to options did not work for us when trying to redo another engineer's implementation. We were too busy.

**Comment by kigonya** [comment]
Yeah... I tried exactly that and it did not fully work. I believe there was some customization on our end that might have complicated things... probably due to apache settings in remote servers for determining the urls... dunno yet.

He had the following:
`        self.swagger_iu_spec = api_spec.copy()
        base_path = EnvUtil.get("base_path", None)
        if base_path:
            self.swagger_iu_spec["basePath"] = base_path
`

So in the errors, after the new change, I got:
`    self.swagger_iu_spec = api_spec.copy()
AttributeError: 'Swagger2Specification' object has no attribute 'copy'
`

So I removed ".copy()"
Then got...
`    self.swagger_iu_spec["basePath"] = base_path
TypeError: 'Swagger2Specification' object does not support item assignment
`
Since it looked like the code could do without a "basePath" I removed it entirely.... everything seemed to work but the swagger-ui could not find its json file.... Tried to google and I gave up as others where waiting and there were several apps to update... So I chose to freeze. I was in a hurry... maybe when I get time I'll have another go at it. 

I gave you some above detail in case you can see something that offers a hint as to what is going on ;).
