### ISSUE TITLE
Any ideas to migrate Connexion to Quart base?

### ISSUE THREAD

**Issue by lovesuper** [spec-first/connexion#889]
### Description

Quart is a Python ASGI web microframework. It is intended to provide the easiest way to use asyncio functionality in a web context, especially with existing Flask apps. This is possible as the Quart API is a superset of the **Flask API**.

### Expected behaviour

We can obtain async behaviour.

### Actual behaviour

We have sync behaviour.

### Additional info:
https://github.com/pgjones/quart

**Comment by dtkav** [comment]
Hey @lovesuper 
There's a related issue about trying to fix the aiohttp interface to work with existing tests. I believe the goal of this work was also to eventually add quart support: https://github.com/zalando/connexion/pull/828

**Comment by prabhu** [comment]
+1 and +1 for doing Quart separately from aiohttp if possible.

Meanwhile, does connexion work well with aiohttp? I couldn't find much example and was facing a number of errors when trying to port a microservice and always thought it was me!

**Comment by SpudInNZ** [comment]
> Meanwhile, does connexion work well with aiohttp? I couldn't find much example and was facing a number of errors when trying to port a microservice and always thought it was me!

By and large it works well. But you'll be digging into the source code at times to figure things out, because the documentation is sparse and oftentimes you can't tell if the docs are referring to something that only applies to Flask. It certainly feels like there is friction where Connexion has been adapted to an async model too, processing security headers is synchronous for example.

**Comment by RobbeSneyders** [comment]
Third party ASGI frameworks are supported starting 3.0: https://github.com/spec-first/connexion/issues/1395
