### ISSUE TITLE
Support path parameter with slashes

### ISSUE THREAD

**Issue by joe42** [spec-first/connexion#946]
### Description
It would be great to have support for a path that can capture slahes.
So when we GET
* /static-files/foo
* /static-files/foo/bar/baz
It will be matched by a rule like
/static-files/{path}
The use case is the routing of a single page application, which has to deal out files from different paths depending on whether the request is a file (respond with the file), or a site (respond with index.html).
A simple static folder is not sufficient to achieve this behavior.

### Additional info:

Related: https://github.com/OAI/OpenAPI-Specification/issues/892

**Comment by drummerwolli** [comment]
I doubt that connexion will implement support for this before the OpenAPI specification on this is clarified. Also, I doubt that this will get specified/allowed, mostly because then specifying/documenting an API becomes useless if those ambiguities (sometimes its a path to a file, sometimes its a "real" HTTP path parameter) are introduced. How do you know which request is now doing what exactly?

would this be a workaround (which I would consider anyways the cleaner solution) for your use-case?

```
/static-files?file=foo/bar/baz
```

**Comment by RobbeSneyders** [comment]
You can do this with `format=path`.

**Comment by joe42** [comment]
@RobbeSneyders Thanks for the concise answer :)

**Comment by RobbeSneyders** [comment]
@joe42 there was a big backlog of old issues, so trying to close them efficiently :slightly_smiling_face: 
Let me know if you need more support!

**Comment by joe42** [comment]
Awesome. I am following some of the issues and really appreciate the effort!
