### ISSUE TITLE
replace ujson with rapidjson

### ISSUE THREAD

**Issue by kornicameister** [spec-first/connexion#989]
### Description

`ujson` seems to be long gone project. 
What if we use something little more "today" like [rapidjson](https://github.com/python-rapidjson/python-rapidjson)

### Expected behaviour

`connexion` uses actively developed library `rapidjson` instead of old `ujson`

### Actual behaviour

`connexion` uses old `ujson`

**Comment by kornicameister** [comment]
@dtkav what do you think of that?

**Comment by cognifloyd** [comment]
ujson is no longer used. It was removed in #851 to allow using a custom JSONEncoder which ujson didn't support.
rapidjson does not support the `cls` kwarg on dumps. rapidjson does however have an alternative to JSONEncoder. So a PR to support this would need to move that into the Jsonifier and then use Jsonifier to hide the difference between using stdlib json and rapidjson.

Here are some resources about the rapidjson `Encoder` that replaces `dumps(cls=JSONEncoder)`
https://github.com/python-rapidjson/python-rapidjson/issues/111#issuecomment-424219748
https://python-rapidjson.readthedocs.io/en/latest/encoder.html

Here are the pieces that might need to be adjusted to work with rapidjson:
- `connexion/jsonifier.py` implements `JSONEncoder` and `Jsonifier`
- `connexion/apis/aiohttp_api.py` has `Jsonifier(cls=JSONEncoder)` defaulting to using stdlib `json` and our custom JSONEncoder.
- `connexion/apis/flask_api.py` has `Jsonifier(flask.json, indent=2)` which uses json from itsdangerous (either `simplejson` or stdlib `json`) via flask. And Flask provides its own JSONEncoder.
- `connexion/apis/abstract.py` has `Jsonifier()` defaulting to stdlib `json` without the custom JSONEncoder - but that isn't used anywhere, since it is overriden for both aiohttp and flask.

Both Flask's and our JSONEncoder support `datetime.datetime`, `datetime.date`, and `UUID`. Flask's JSONEncoder also supports `dataclasses`, but our JSONEncoder (used with aiohttp) does not. That might be interesting to support.

This is the bug for supporting rapidjson in flask:
https://github.com/pallets/flask/issues/1602
It is closed, but looks like there was something that might allow rapidjson there.

**Comment by RobbeSneyders** [comment]
Closing this as `ujson` was removed and the user can provide their own `JSONEncoder`.
